[tool.bumpversion]
current_version = "1.1.2"
commit = true
tag = true
tag_name = "{new_version}"

[[tool.bumpversion.files]]
filename = "./pom.xml"

[[tool.bumpversion.files]]
filename = "./src/main/java/net/nharyes/secrete/Main.java"
